### ISSUE TITLE
Create new repo (arfc/2018-westphal-antpc)

### ISSUE THREAD

**Issue by katyhuff** [gtw2/2018-antpc-summary#1]
To avoid complicated permissions issues, publications for the research group can reside in arfc which automagically allows group members (me, etc.) to collaborate. 

To close this issue:

1) go to github.com/arfc and create a new repo (2018-westphal-antpc)
2) in your terminal, navigate to where you've cloned the repo
3) add your new repo as a remote `git remote add arfc git@github.com:arfc/2018-westphal-antpc`
4) push your repo to that remote `git push arfc master`

**Comment by gtw2** [comment]
[github.com/arfc/2018-westphal-antpc](url) has been created and the arfc branch holds all files.
